# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "xhci_pci"
    "usb_storage"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0420340b-01d5-44cc-8a18-b99fcdc25dd6";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/9F31-F630";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/fd7fa047-a4ae-4489-986a-798ff85ff85f"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp2s0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlo1.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # specialisation = {
  #   nvidia.configuration = {
  #     # Nvidia Configuration 
  #     services.xserver.videoDrivers = [ "nvidia" ];
  #     hardware.opengl.enable = true;
  #
  #     # Optionally, you may need to select the appropriate driver version for your specific GPU. 
  #     hardware.nvidia.package = config.boot.kernelPackages.nvidiaPackages.stable;
  #
  #     # nvidia-drm.modeset=1 is required for some wayland compositors, e.g. sway 
  #     hardware.nvidia.modesetting.enable = true;
  #
  #     hardware.nvidia.prime = {
  #       sync.enable = true;
  #
  #       # Bus ID of the NVIDIA GPU. You can find it using lspci, either under 3D or VGA 
  #       nvidiaBusId = "PCI:1:0:0";
  #
  #       # Bus ID of the Intel GPU. You can find it using lspci, either under 3D or VGA 
  #       # intelBusId = "PCI:0:2:0";
  #       amdgpuBusId = "PCI:6:0:0";
  #     };
  #   };
  # };

  specialisation."VFIO".configuration = {
    system.nixos.tags = [ "with-vfio" ];
    vfio.enable = true;
  };
  hardware = {
    # enableAllFirmware = true;
    # cpu.amd.updateMicrocode = true; # needs unfree
    opengl.enable = true;
    graphics.enable32Bit = true;
  };

  hardware.nvidia.prime = {
    sync.enable = true;
    nvidiaBusId = "PCI:1:0:0";
    amdgpuBusId = "PCI:6:0:0";
    # intelBusId = "PCI:0:2:0";
  };
  hardware.nvidia.modesetting.enable = true;
}
