-- Surround selections, add quotes, etc.
return {
  -- {
  --   "kylechui/nvim-surround",
  --   event = { "BufReadPre", "BufNewFile" },
  --   opts = {
  --     keymaps = {
  --       insert = false,
  --       insert_line = false,
  --       visual_line = false,
  --       -- normal = "yz",
  --       -- normal_cur = "yzz",
  --       -- normal_line = "yZ",
  --       -- normal_cur_line = "yZZ",
  --       -- visual = "Z",
  --       normal = "yz",
  --       normal_cur = "mzz",
  --       normal_line = "mZ",
  --       normal_cur_line = "mZZ",
  --       visual = "Z",
  --     },
  --   },
  -- },
}
