#!/usr/bin/env bash

while getopts "w:d:" opt; do
  case $opt in
  w) week=$OPTARG ;;
  d) today=$OPTARG ;;
  *)
    echo "Usage: $0 [-w week] [-d day]" >&2
    exit 1
    ;;
  esac
done

week=$(date +"%V")
today=$(date +"%Y-%m-%d")
tomorrow=$(date -d "tomorrow" +"%Y-%m-%d")
yesterday=$(date -d "yesterday" +"%Y-%m-%d")
file="$ZETTELKASTEN/daily/$today.md"

cd "$ZETTELKASTEN" || exit

new_note() {
  touch "$file"

  # Format the file with the daily template
  cat <<EOF >"$file"
# $today

[[$yesterday]] - [[$tomorrow]]

## Tasks
- [ ] 

## Habits?


## Exercise


## Log
EOF

}

# If the daily note does not exist, create a new one.
# this uses the test command with the -f flag.
if [ ! -f "$file" ]; then
  echo "File does not exist, creating new daily note."
  new_note
fi

# Open the daily note at the bottom of the file in insert mode and run NoNeckPain to make it center
nvim '+ normal Gzzo' "$file"
