#!/usr/bin/env bash

today=$(date +"%V")
# tomorrow=$(date -d "tomorrow" +"%Y-%m-%d")
# yesterday=$(date -d "yesterday" +"%Y-%m-%d")
file="$ZETTELKASTEN/weekly/$today.md"

cd "$ZETTELKASTEN" || exit

new_note() {
  touch "$file"

  # Format the file with the daily template
  cat <<EOF >"$file"
# W$today
## Objectives


## Tasks
1. 
2.
3.
4.
5.
6.
7.

## Habits?


## Exercise


## Log
EOF

}

# If the daily note does not exist, create a new one.
# this uses the test command with the -f flag.
if [ ! -f "$file" ]; then
  echo "File does not exist"
  new_note
fi

# Open the daily note at the bottom of the file in insert mode and run NoNeckPain to make it center
nvim '+ normal Gzzo' "$file"
